### ISSUE TITLE
Extension leaves trailing whitespace

### ISSUE THREAD

**Issue by teokk1** [j-brooke/FracturedJsonVSC#10]
The extension is fantastic, but the way it adds spaces doesn't work contextually and it adds spaces to the ends of lines as well. This triggers any trailing whitespace detection and can be quite annoying if one uses something like that.

**Comment by j-brooke** [comment]
I understand your complaint about spaces at the end of lines, but I'm not sure what you mean by "trailing whitespace detection".  Will you please elaborate?

Certainly some many diff tools will point out a difference in trailing whitespace.  But if you're reformatting a document you would expect a ton of differences anyway.

My assumption up until now was that if it was a hassle people would use VSCode's "Trim Trailing Whitespace On Save" setting, or perhaps the manual trim command.  Are there situations where those aren't viable solutions?

**Comment by teokk1** [comment]
Certainly. There are a lot of extensions and tools like this one: https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces (which is what I use), and trailing whitespace checks can also be a part of linting or CICD pipelines. They aren't in our case, but it's definitely doable and makes sense to do.

**Comment by teokk1** [comment]
However, now that I linked this, I realized there's a setting to trim on save, so that's gonna solve my particular problem.

**Comment by j-brooke** [comment]
Fixed in version 3.1.0.
