### ISSUE TITLE
VS code default JSON formatter

### ISSUE THREAD

**Issue by alexleduc76** [j-brooke/FracturedJsonVSC#2]
Hi,

I tried configuring this as the default JSON formatter and the editor doesn't seem to be be able to use it. Any chance this can be fixed so that we don't have to use the command palette to trigger your formatting and instead let it use Format On Save with your formatter?

**Comment by j-brooke** [comment]
I didn't know that was even possible.  I'll look into it.  Thanks for the feedback.

**Comment by alexleduc76** [comment]
Thanks!

**Comment by j-brooke** [comment]
I appreciate you bringing this to my attention.  I didn't know about the formatting API at all.  (VSCode really does have a lot going on.)  I hope to get a new package out in a day or two.
