### ISSUE TITLE
Compact Nesting

### ISSUE THREAD

**Issue by shanimal** [j-brooke/FracturedJsonVSC#4]
Is compact nesting possible?
```
[{
    "nested": "object 1"
}, {
    "nested": "object 2"
}]
```

**Comment by j-brooke** [comment]
Will you please write up some more details about what you're looking for, @shanimal ?  I think I get the general idea, but there are a lot of specific cases that I don't want to guess at.  Does this apply just to arrays, or objects too?  How does it affect inlined elements, compared to multiline compact arrays or fully expanded elements?

**Comment by shanimal** [comment]
The example was really about grouping the wrappers where possible `[{` and putting the start+end on one line `}, {`

So if I used some data from your awesome online [Browser Formatter](https://j-brooke.github.io/FracturedJson/), set the "Maximum Inline Complexity" to "1", and checked "Compact Brackets" I might see this...
```
    "ArrayColumnsObjectRows": [{
          "hp": 400,
          "type": "turret",
          "loc": {"x": 47, "y": -4},
          "flags": "S"
      }, {
          "type": "assassin",
          "hp": 80,
          "loc": {"x": 12, "y": 6},
          "flags": "Q"
      }, {
          "type": "berserker",
          "hp": 150,
          "loc": {"x": 0, "y": 0}
      }, {
          "loc": {"x": 10, "y": -14},
          "type": "pittrap",
          "flags": "S,I"
      }]
```

I just realized this defeats "Maximum Inline Complexity" :( for case like this
```
    "ArrayColumnsObjectRows": [{
          "hp": 400,
          "type": "turret",
          "loc": {"x": 47, "y": -4},
          "flags": "S"
      }, { 
          "type": "assassin" 
      }, {
          ...
```

Although this doesn't seem too terrible...
```    
    "ArrayColumnsObjectRows": [{
          "hp": 400,
          "type": "turret",
          "loc": {"x": 47, "y": -4},
          "flags": "S"
      }, 
      { "type": "assassin" }, 
      {
          "type": "berserker",
          "hp": 150,
          "loc": {"x": 0, "y": 0}
      }, {
          ...
```

**Comment by j-brooke** [comment]
In the simple cases examined above it looks doable, but when extended to a more general case it raises some tricky questions.

For example:
```
[[{
        "foo": 1,
        "bar": 2,
        "baz": 3
    },{
        "foo": 1,
        "bar": 2,
        "baz": 3
    }],[{
        "foo": 1,
        "bar": 2,
        "baz": 3
    }]]

```

The indentation levels above are different from the expanded case.  And it's misleading, by suggesting that elements with different depths actually have the same depth.

I think that this feature would lead to a minefield of special case code that would be very difficult to maintain or expand.

**Comment by shanimal** [comment]
Ya, that makes sense. 

The above example should look like the following, but it's still a bit awkward.

```
[[{
    "foo": 1,
    "bar": 2,
    "baz": 3
},{
    "foo": 1,
    "bar": 2,
    "baz": 3
}],[{
    "foo": [{
        "foo": 1,
        "bar": 2,
        "baz": 3
    },{
        "foo": 1,
        "bar": 2,
        "baz": 3
    },{
        "foo": 1,
        "bar": 2,
        "baz": 3
    }]
}]]
```
