### ISSUE TITLE
[feature request] Allow comments in JSON file

### ISSUE THREAD

**Issue by davidevertuani** [j-brooke/FracturedJsonVSC#6]
Feature request, which is already tackled by the readme, but:

Would be great to have the ability to opt-in into "non-pure-JSON compliant mode", or whatever, to allow comments within the document.
Where I work, comments in JSON are extensively used to document the provenience of the data (aerospace stuff, hence many sources) or to enhance readability by colleagues, and this breaks compatibility with the tool. We find that compacting the document highly increases the usability of JSON files, and honestly FracturedJson does that better then the others, but right now we feel like this feature is missing.

Ideal behavior: lines starting with `//` shall be ignored by the tabulation logic, and simply aligned with the current body indentation.
Trailing comments could be aligned at the tail of the longest tabulated line.

Would it be possible to add this as feature / opt-in functionality?

Thanks, keep up the great work!

**Comment by j-brooke** [comment]
Comments will be supported in version 3.  (It's out for the .NET and web formatter versions.  It'll be a while before I upgrade the VSCode plugin.)

**Comment by j-brooke** [comment]
Version 3 is now available, and comments are supported.

**Comment by davidevertuani** [comment]
So great to see support for comments, thanks man.
