### ISSUE TITLE
[question] is it possible to have inline or one per line if inline is too long?

### ISSUE THREAD

**Issue by gregveres** [j-brooke/FracturedJsonVSC#7]
I formatted a json file and recieved this:
```
  "extends": [
    "../../.eslintrc.json", "plugin:vue/essential", "@vue/typescript/recommended",
    "prettier"
  ],
```

I installed your extension becuase I really wanted to preserve single line arrays and it is fantastic for that. But I would like to see if I can configure it to try to stick everyting on a single line and if it can't, then go with one per line.  So I only want to see one of these options, I never want to see the option above. 

```
  "extends": [ "../../.eslintrc.json", "plugin:vue/essential", "@vue/typescript/recommended", "prettier" ],
```

```
  "extends": [
    "../../.eslintrc.json", 
    "plugin:vue/essential", 
    "@vue/typescript/recommended",
    "prettier"
  ],
```

Is that possible?

**Comment by j-brooke** [comment]
Yes, there are a couple ways to accomplish what you're looking for by adjusting the settings.  (The easiest way to get at the settings is probably to go to the Extensions tab, then click on the gear symbol next to FractureJson and select Extension Settings.)

The most straightforward change you can make, if it suits your needs, is increase `Max Inline Length`.  (That's the length of the content part of a line.  It doesn't take indentation into account.)  But of course, you might not like how it looks if you increase that too much.

The setting you're probably looking for is `Max Compact Array Complexity`.  Setting that to 0 will disable multi-line arrays with multiple items per line, which is what I think you're looking for.  The down-side is it will do this for all arrays, so if your document also has, for example, long lists of numbers, it might not be worth it.

Example.  (MaxInlineLength = 80, MaxCompactArrayComplexity = *1* ):
```
{
    "extends": [
        "../../.eslintrc.json", "plugin:vue/essential", "@vue/typescript/recommended", 
        "prettier"
    ],
    "ShortArray": [false, false, true, false],
    "LongArray": [
          2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,  43,  47,  53, 
         59,  61,  67,  71,  73,  79,  83,  89,  97, 101, 103, 107, 109, 113
    ]
}
```

Example.  (MaxInlineLength = 80, MaxCompactArrayComplexity = *0* )
```
{
    "extends": [
        "../../.eslintrc.json",
        "plugin:vue/essential",
        "@vue/typescript/recommended",
        "prettier"
    ],
    "ShortArray": [false, false, true, false],
    "LongArray": [
          2,
          3,
          5,
          7,
         11,
         13,
         17,
         19,
         23,
         29,
         31,
         37,
         41,
         43,
         47,
         53,
         59,
         61,
         67,
         71,
         73,
         79,
         83,
         89,
         97,
        101,
        103,
        107,
        109,
        113
    ]
}
```

**Comment by gregveres** [comment]
Thank you. I will give Max compact array complexity of 0 a try.
