### ISSUE TITLE
Can't use Formatter on perfectly valid JSON files with custom file extension

### ISSUE THREAD

**Issue by pibcht** [j-brooke/FracturedJsonVSC#8]
Hi,

First of all, this is a really nice tool! 👍

Then my issue:
I've created a json based language with it's own file extension (let's say .foo).
It's a perfectly valid json file, but I've created custom syntactic parser/colorizer in VS Code
I want to use FracturedJson to format those files
I can't set "files.associations" for this as it override colorizer
Command: Format JSON Document work perfectly fine but [Alt] + [Shift] + [F]

Can you let us define custom file extensions for your formatter?

Nota: Sorry, I posted this issue in wrong repo (as it concern only VS Code). Closed and reopened here.
→ https://github.com/j-brooke/FracturedJson/issues/14

**Comment by j-brooke** [comment]
Closing this issue.  So far as I know, this isn't possible.  I don't think it's worth spending a lot of effort chasing down.  (But if I'm wrong, I'm happy to look at a pull request, of course.)
