### ISSUE TITLE
Comma padding (fracturedjsonvsc.v3.CommaPadding) applied before newline

### ISSUE THREAD

**Issue by davidevertuani** [j-brooke/FracturedJsonVSC#9]
The new setting "V3: Comma Padding" adds a space after commas.
This is ok, and desired, but should not be the case at the end of the line.
Turning it off will disable spacing for ALL commas.

_fracturedjsonvsc.v3.CommaPadding = true_
`"anyOf": [ {"type": "number", "default": 1}, {"type": "string"} ], \n`

_fracturedjsonvsc.v3.CommaPadding = false_
`"anyOf": [ {"type": "number","default": 1},{"type": "string"} ],\n`

**Desired behavior:** _fracturedjsonvsc.v3.CommaPadding_ enables/disables spaces after commas within the JSON body. Trailing commas, before newline, are not affected, and a space is never inserted.

_fracturedjsonvsc.v3.CommaPadding = true, desired behaviour_
`"anyOf": [ {"type": "number", "default": 1}, {"type": "string"} ],\n`

**Comment by j-brooke** [comment]
Fixed in version 3.1.0.
